# Generated by Django 3.1.6 on 2021-03-12 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 12, 10, 0, 7, 638564, tzinfo=utc)),
        ),
    ]
