# Generated by Django 3.1.6 on 2021-03-16 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Eventtt',
        ),
    ]
