# Generated by Django 3.1.6 on 2021-03-13 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='type',
            new_name='Group',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='role',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
