# Generated by Django 3.1.6 on 2021-03-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210313_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Group',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='user.role'),
            preserve_default=False,
        ),
    ]
