# Generated by Django 3.1.6 on 2021-03-13 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_auto_20210313_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='role',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
